# Generated by Django 5.2.8 on 2025-11-24 21:18

import django.db.models.deletion
import identification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turtle',
            fields=[
                ('id', models.BigIntegerField(default=identification.models.generate_turtle_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('biology_id', models.CharField(blank=True, help_text='Biology Dept ID (e.g., F101)', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurtleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='turtles/original/')),
                ('mirror_image', models.ImageField(blank=True, null=True, upload_to='turtles/mirror/')),
                ('vlad_blob_original', models.BinaryField(blank=True, null=True)),
                ('vlad_blob_mirror', models.BinaryField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turtle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='identification.turtle')),
            ],
        ),
    ]
