# Generated by Django 5.2.8 on 2025-11-30 21:54

import django.db.models.deletion
import identification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turtle',
            fields=[
                ('id', models.BigIntegerField(default=identification.models.generate_turtle_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('J', 'Juvenile'), ('U', 'Unknown')], default='U', max_length=1)),
                ('turtle_number', models.IntegerField(help_text='The ID number assigned by Bio Dept')),
                ('location_state', models.CharField(help_text='State (e.g., Kansas)', max_length=100)),
                ('location_specific', models.CharField(help_text='Specific Location (e.g., Lawrence)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurtleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=identification.models.turtle_image_path)),
                ('mirror_image', models.ImageField(blank=True, null=True, upload_to=identification.models.turtle_mirror_path)),
                ('vlad_blob_original', models.BinaryField(blank=True, null=True)),
                ('vlad_blob_mirror', models.BinaryField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turtle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='identification.turtle')),
            ],
        ),
    ]
